### ISSUE TITLE
Request failed 404 Error

### ISSUE THREAD

**Issue by alsafoo** [dnnsoftware/Dnn.Evoq.LiquidContent.Samples.Public#4]
Hi, 

Whenever i run yarn install command i get 404 error, i added ansi-styles (2.2.1) in devdependencies in package.json....

Error: https://registry.yarnpkg.com/npm/ansi-styles/-/ansi-styles-2.2.1.tgz: Request failed "404 Not Found"
      at new ResponseError (C:\Program Files (x86)\Yarn\lib\cli.js:238:112)
      at Request.<anonymous> (C:\Program Files (x86)\Yarn\lib\cli.js:61626:26)
      at emitOne (events.js:115:13)
      at Request.emit (events.js:210:7)
      at Request.module.exports.Request.onRequestResponse (C:\Program Files (x86)\Yarn\lib\cli.js:133316:10)
      at emitOne (events.js:115:13)
      at ClientRequest.emit (events.js:210:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:563:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
      at TLSSocket.socketOnData (_http_client.js:452:20)

**Comment by tpluscode** [comment]
@mean2me could you have a look in a spare moment to see what is wrong?
